### ISSUE TITLE
Generated project is broken

### ISSUE THREAD

**Issue by romikoops** [strongqa/howitzer#191]
Test case:
```
howitzer new test_automation --cucumber  
cd test_automation
bundle install
rake features
```

Expected result: Tests suit should run
Actual result: 

```
cannot load such file -- /Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/web/pages/example_menu (LoadError)
/Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/web/pages/example_page.rb:1:in `require_relative'
/Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/web/pages/example_page.rb:1:in `<top (required)>'
/Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/config/boot.rb:12:in `require'
/Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/config/boot.rb:12:in `block in <top (required)>'
/Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/config/boot.rb:12:in `each'
/Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/config/boot.rb:12:in `<top (required)>'
/Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/features/support/env.rb:3:in `require_relative'
/Users/romikoops/RubyWS/strongqa/test_howitzer_project1/test_automation/features/support/env.rb:3:in `<top (required)>'
```

**Comment by romikoops** [comment]
Fixed with commit 132a3c5
